### ISSUE TITLE
Cannot resolve std::string::String: std::borrow

### ISSUE THREAD

**Issue by Manah7** [gbip/herkulex_driver#1]
Code fails to compile with nightly (2019/01/08) or stable :
```
error[E0283]: type annotations required: cannot resolve std::string::String: std::borrow::Borrow<_>
   --> src/ui.rs:325:12
    |
325 |     result.set_on_submit(move |s, connection| {
    |
```
Also objects without an explicit dyn are seem deprecated.

**Comment by gbip** [comment]
You are looking at the wrong repo, maybe you want to try this [one ]( https://github.com/gbip/drs_0x01_driver)?
